"""i18n — English/Italian localization for CLI and HTML output.

Usage:
    from .i18n import t, set_lang, get_lang, detect_lang
    set_lang("it")  # or "en"
    print(t("error_no_api_key"))  # → Italian string
    print(t("error_no_api_key", lang="en"))  # → English string
"""

from __future__ import annotations

import os

_LANG: str | None = None

STRINGS: dict[str, dict[str, str]] = {
    # CLI errors / messaggi CLI
    "error_no_api_key": {
        "en": "Error: API key not set. Set ANTHROPIC_API_KEY or use --mock.",
        "it": "Errore: API key non impostata. Imposta ANTHROPIC_API_KEY oppure usa --mock.",
    },
    "error_starlette_missing": {
        "en": "Error: starlette not installed. Install with: pip install starlette",
        "it": "Errore: starlette non installato. Installa con: pip install starlette",
    },
    "error_uvicorn_missing": {
        "en": "Error: uvicorn not installed. Install with: pip install uvicorn",
        "it": "Errore: uvicorn non installato. Installa con: pip install uvicorn",
    },
    "server_started": {
        "en": "Tavolarotonda server started — http://localhost:{port}",
        "it": "Tavolarotonda server avviato — http://localhost:{port}",
    },
    "route_health": {
        "en": "GET  /health             — health check",
        "it": "GET  /health             — health check",
    },
    "route_mcp": {
        "en": "POST /mcp                — MCP JSON-RPC endpoint",
        "it": "POST /mcp                — endpoint MCP JSON-RPC",
    },
    "route_obsidian_read": {
        "en": "GET  /api/obsidian/topic?topic=X — read topic from vault",
        "it": "GET  /api/obsidian/topic?topic=X — leggi topic dal vault",
    },
    "route_obsidian_save": {
        "en": "POST /api/obsidian/save  — save session to vault",
        "it": "POST /api/obsidian/save  — salva sessione nel vault",
    },
    # HTML template strings / stringhe template HTML
    "audit_report": {
        "en": "Audit Report — {title}",
        "it": "Report di Audit — {title}",
    },
    "generated": {
        "en": "Generated: {date}",
        "it": "Generato: {date}",
    },
    "confidence": {
        "en": "Confidence",
        "it": "Confidenza",
    },
    "verdict": {
        "en": "Verdict",
        "it": "Verdetto",
    },
    "verdict_council": {
        "en": "Council Verdict",
        "it": "Verdetto del Council",
    },
    "pro_arguments": {
        "en": "Pro Arguments (confirmed strengths)",
        "it": "Pro (vantaggi confermati)",
    },
    "contra_arguments": {
        "en": "Contra Arguments (confirmed weaknesses)",
        "it": "Contro (svantaggi confermati)",
    },
    "strong_points": {
        "en": "Strong Points",
        "it": "Punti di Forza",
    },
    "critical_issues": {
        "en": "Critical Issues",
        "it": "Criticità",
    },
    "recommendations": {
        "en": "Recommendations (concrete actions)",
        "it": "Consigli (azioni concrete)",
    },
    "minority_report": {
        "en": "Minority Report (contra case)",
        "it": "Minority Report (caso CONTRO)",
    },
    "open_questions": {
        "en": "Open Questions",
        "it": "Domande Aperte",
    },
    "per_agente": {
        "en": "Per Agent",
        "it": "Per Agente",
    },
    "footer_generated": {
        "en": "Generated by tavolarotonda v0.1.0 — Council of High Intelligence pattern "
             "(18 personas, polarity pairs, adversarial evidence, anti-groupthink).",
        "it": "Generato da tavolarotonda v0.1.0 — Council of High Intelligence pattern "
              "(18 personas, polarity pairs, adversarial evidence, anti-groupthink).",
    },
    "qa_title": {
        "en": "Q&A Analysis — {topic}",
        "it": "Analisi Q&A — {topic}",
    },
    "qa_meta": {
        "en": "Multi-question Q&A template. Fill in questions, the council answers in parallel and generates comparative analysis.",
        "it": "Template Q&A multi-domanda. Compila le domande, il council risponde in parallelo e genera analisi comparativa.",
    },
    "fill_template": {
        "en": "Fill in your answers below",
        "it": "Inserisci le tue risposte qui sotto",
    },
    "comparative_analysis": {
        "en": "Comparative Analysis",
        "it": "Analisi Comparativa",
    },
    "questions_label": {
        "en": "Questions",
        "it": "Domande",
    },
    "add_question": {
        "en": "+ Add question",
        "it": "+ Aggiungi domanda",
    },
    "run_analysis": {
        "en": "RUN MULTI-AGENT ANALYSIS",
        "it": "ESEGUI ANALISI MULTI-AGENTE",
    },
    "results": {
        "en": "Results",
        "it": "Risultati",
    },
    "results_placeholder": {
        "en": "Press \"RUN ANALYSIS\" to populate this section.",
        "it": "Premi \"ESEGUI ANALISI\" per popolare questa sezione.",
    },
    "footer_qa": {
        "en": "Q&A template generated by tavolarotonda.",
        "it": "Template Q&A generato da tavolarotonda.",
    },
}


def detect_lang() -> str:
    """Auto-detect from LANG/LANGUAGE env vars."""
    lang = os.environ.get("LANG", "") or os.environ.get("LANGUAGE", "") or ""
    if lang.lower().startswith("it"):
        return "it"
    return "en"


def get_lang() -> str:
    """Return active language (default: detect)."""
    global _LANG
    if _LANG is None:
        _LANG = detect_lang()
    return _LANG


def set_lang(lang: str) -> None:
    """Set active language ('en' or 'it')."""
    global _LANG
    _LANG = lang if lang in ("en", "it") else "en"


def reset_lang() -> None:
    """Reset to auto-detection (clears cached language)."""
    global _LANG
    _LANG = None


def t(key: str, **kwargs) -> str:
    """Translate key to active language. Falls back to EN."""
    lang = get_lang()
    strings = STRINGS.get(key, {})
    text = strings.get(lang, strings.get("en", key))
    return text.format(**kwargs) if kwargs else text
